NAME = animals

SRC_FILES = src/main.cpp src/Animal.cpp src/Dog.cpp src/Cat.cpp

OBJ_DIR = objs/
OBJ_FILES = $(notdir $(SRC_FILES:.cpp=.o))
OBJS = $(addprefix $(OBJ_DIR), $(OBJ_FILES))

DEP_FILES = $(SRC_FILES:.cpp=.d)
DEPS = $(addprefix $(OBJ_DIR), $(DEP_FILES))

CC = g++
CFLAGS = -std=c++98 -Wall -Werror -Wextra -MMD
RM = rm -f
INCLUDE = -I includes

all: $(NAME)

$(NAME): $(OBJ_DIR) $(OBJS)
	$(CC) $(CFLAGS) $(INCLUDE) $(OBJS) -o $@

$(OBJ_DIR):
	mkdir -p $@

$(OBJ_DIR)%.o: src/%.cpp
	$(CC) $(CFLAGS) $(INCLUDE) -c $< -o $@

clean:
	$(RM) $(OBJS) $(DEPS)

fclean: clean
	$(RM) -r $(OBJ_DIR)
	$(RM) $(NAME)

re: fclean all

-include $(DEPS)

.PHONY: all clean fclean re
